"""drop the demo-era fee, hostel, facility, placement and nearby tables

Revision ID: 2d97fb97e535
Revises: a6062870001d
Create Date: 2026-10-02 10:04:16.151210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2d97fb97e535'
down_revision: Union[str, None] = 'a6062870001d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.drop_index('ix_fees_college_course_id')

    op.drop_table('fees')
    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.drop_index('ix_hostels_college_id')

    op.drop_table('hostels')
    with op.batch_alter_table('nearby_places', schema=None) as batch_op:
        batch_op.drop_index('ix_nearby_places_college_id')

    op.drop_table('nearby_places')
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.drop_index('ix_facilities_college_id')

    op.drop_table('facilities')
    with op.batch_alter_table('placements', schema=None) as batch_op:
        batch_op.drop_index('ix_placements_college_id')

    op.drop_table('placements')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('college_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('placement_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_package', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('median_package', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('highest_package', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('major_recruiters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('academic_year', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_verified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('verification_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name='placements_college_id_fkey'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='placements_course_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='placements_pkey')
    )
    with op.batch_alter_table('placements', schema=None) as batch_op:
        batch_op.create_index('ix_placements_college_id', ['college_id'], unique=False)

    op.create_table('facilities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('college_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('facility_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('verification_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name='facilities_college_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='facilities_pkey')
    )
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.create_index('ix_facilities_college_id', ['college_id'], unique=False)

    op.create_table('nearby_places',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('college_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('place_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('distance_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('approx_monthly_rent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name='nearby_places_college_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='nearby_places_pkey')
    )
    with op.batch_alter_table('nearby_places', schema=None) as batch_op:
        batch_op.create_index('ix_nearby_places_college_id', ['college_id'], unique=False)

    op.create_table('hostels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('college_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hostel_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('room_types', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('fee_annual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('facilities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('rules', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('distance_from_academic_block_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('academic_year', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_verified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('verification_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name='hostels_college_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='hostels_pkey')
    )
    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.create_index('ix_hostels_college_id', ['college_id'], unique=False)

    op.create_table('fees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('college_course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tuition_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('admission_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('exam_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hostel_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mess_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('security_deposit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('other_charges', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('academic_year', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_verified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('verification_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['college_course_id'], ['college_courses.id'], name='fees_college_course_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fees_pkey')
    )
    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.create_index('ix_fees_college_course_id', ['college_course_id'], unique=False)

    # ### end Alembic commands ###
