"""roadmaps and progress (Phase 5)

Versioned roadmap trees with per-node progress and the changes each version made, and skill
measurements over time. See docs/design/09-roadmap-model.md and 14-phase5-plan.md.

Revision ID: 391bdf1ab61c
Revises: f5da3e325211
Create Date: 2026-10-01 23:45:02.671077

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '391bdf1ab61c'
down_revision: Union[str, None] = 'f5da3e325211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('focus_career', sa.String(length=80), nullable=True),
    sa.Column('branches', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dropped', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('hours_per_week', sa.Integer(), nullable=False),
    sa.Column('difficulties', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('active_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_profile_id')
    )
    op.create_table('skill_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('skill_key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_profile_id', 'skill_key', 'source_kind', 'source_id', name='uq_skill_measurement')
    )
    with op.batch_alter_table('skill_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_measurements_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('roadmap_progress',
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('node_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.PrimaryKeyConstraint('roadmap_id', 'node_key')
    )
    op.create_table('roadmap_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rationale', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inputs_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roadmap_id', 'version_no', name='uq_roadmap_version')
    )
    with op.batch_alter_table('roadmap_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmap_versions_roadmap_id'), ['roadmap_id'], unique=False)

    op.create_table('roadmap_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('op', sa.String(length=20), nullable=False),
    sa.Column('node_key', sa.String(length=160), nullable=False),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reason', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['roadmap_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmap_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmap_changes_version_id'), ['version_id'], unique=False)

    op.create_table('roadmap_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('node_key', sa.String(length=160), nullable=False),
    sa.Column('parent_key', sa.String(length=160), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('title', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prerequisites', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('est_hours', sa.Float(), nullable=True),
    sa.Column('window', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('kg_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attrs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['roadmap_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'node_key', name='uq_roadmap_node')
    )
    with op.batch_alter_table('roadmap_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmap_nodes_version_id'), ['version_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmap_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_nodes_version_id'))

    op.drop_table('roadmap_nodes')
    with op.batch_alter_table('roadmap_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_changes_version_id'))

    op.drop_table('roadmap_changes')
    with op.batch_alter_table('roadmap_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_versions_roadmap_id'))

    op.drop_table('roadmap_versions')
    op.drop_table('roadmap_progress')
    with op.batch_alter_table('skill_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_measurements_student_profile_id'))

    op.drop_table('skill_measurements')
    op.drop_table('roadmaps')
    # ### end Alembic commands ###
