"""agenda marks (Phase 7)

Revision ID: 5be5f6e26ab1
Revises: f470369c50fc
Create Date: 2026-10-02 15:07:46.174770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5be5f6e26ab1'
down_revision: Union[str, None] = 'f470369c50fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('first_raised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_raised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('times_raised', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_profile_id', 'key', name='uq_agenda_mark')
    )
    with op.batch_alter_table('agenda_marks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agenda_marks_student_profile_id'), ['student_profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda_marks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agenda_marks_student_profile_id'))

    op.drop_table('agenda_marks')
    # ### end Alembic commands ###
