"""assessment instruments, attempts and scores (Phase 3)

Versioned instruments and their items, each attempt a student makes, their responses, scores per
dimension, and snapshots of the career directions. See docs/design/12-phase3-plan.md.

Revision ID: 7255fff01d6b
Revises: c85d25b5c898
Create Date: 2026-10-01 18:13:17.355626

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7255fff01d6b'
down_revision: Union[str, None] = 'c85d25b5c898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('title', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('scoring_method', sa.String(length=30), nullable=False),
    sa.Column('est_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content_sha', sa.String(length=64), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'version', name='uq_instrument_version')
    )
    op.create_table('assessment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('form', sa.String(length=5), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['assessment_instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'key', name='uq_item_key')
    )
    with op.batch_alter_table('assessment_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_items_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('assessment_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=5), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('path', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('legacy_assessment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['assessment_instruments.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_attempts_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('career_alignment_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('inputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('career_alignment_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_alignment_snapshots_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('assessment_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('interpreted_by', sa.String(length=10), nullable=False),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['assessment_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'item_id', name='uq_response_item')
    )
    with op.batch_alter_table('assessment_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_responses_attempt_id'), ['attempt_id'], unique=False)

    op.create_table('assessment_scores',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('dimension_key', sa.String(length=60), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('n_items', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], ),
    sa.PrimaryKeyConstraint('attempt_id', 'dimension_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_scores')
    with op.batch_alter_table('assessment_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_responses_attempt_id'))

    op.drop_table('assessment_responses')
    with op.batch_alter_table('career_alignment_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_alignment_snapshots_student_profile_id'))

    op.drop_table('career_alignment_snapshots')
    with op.batch_alter_table('assessment_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_attempts_student_profile_id'))

    op.drop_table('assessment_attempts')
    with op.batch_alter_table('assessment_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_items_instrument_id'))

    op.drop_table('assessment_items')
    op.drop_table('assessment_instruments')
    # ### end Alembic commands ###
