"""practice question bank and attempts

Revision ID: 8e29031be361
Revises: c411ec4ada55
Create Date: 2026-09-18 11:02:28.100093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8e29031be361'
down_revision: Union[str, None] = 'c411ec4ada55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=True),
    sa.Column('class_level', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_subject'), ['subject'], unique=False)

    op.create_table('question_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'exam_id', name='uq_question_exam')
    )
    with op.batch_alter_table('question_exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_exams_exam_id'), ['exam_id'], unique=False)

    op.create_table('test_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('seconds_taken', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('wrong', sa.Integer(), nullable=False),
    sa.Column('unanswered', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('subject_scores', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_attempts_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('attempt_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('selected_index', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempt_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_answers_attempt_id'), ['attempt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_answers_attempt_id'))

    op.drop_table('attempt_answers')
    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_attempts_student_profile_id'))

    op.drop_table('test_attempts')
    with op.batch_alter_table('question_exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_exams_exam_id'))

    op.drop_table('question_exams')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_subject'))

    op.drop_table('questions')
    # ### end Alembic commands ###
