"""career library details and profiles

Revision ID: a35c72e936c2
Revises: 8e29031be361
Create Date: 2026-09-18 14:57:48.909888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a35c72e936c2'
down_revision: Union[str, None] = '8e29031be361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('career_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('profile', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('must', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('details', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.create_unique_constraint("uq_career_options_key", ["key"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('career_options', schema=None) as batch_op:
        batch_op.drop_constraint("uq_career_options_key", type_="unique")
        batch_op.drop_column('details')
        batch_op.drop_column('must')
        batch_op.drop_column('profile')
        batch_op.drop_column('key')

    # ### end Alembic commands ###
