"""facts, sources and the OKF bundle loads

Revision ID: a6062870001d
Revises: 391bdf1ab61c
Create Date: 2026-10-02 01:18:44.483989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.types import Embedding
from sqlalchemy.dialects import postgresql

revision: str = 'a6062870001d'
down_revision: Union[str, None] = '391bdf1ab61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('attribute', sa.String(length=80), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=True),
    sa.Column('fact_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('okf_loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commit', sa.String(length=40), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('concepts', sa.Integer(), nullable=False),
    sa.Column('facts', sa.Integer(), nullable=False),
    sa.Column('problems', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('academic_year', sa.String(length=9), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('entity_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_documents_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_documents_source_id'), ['source_id'], unique=False)
        batch_op.create_index('ix_source_documents_url', ['url'], unique=False)

    op.create_table('doc_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=500), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('entity_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=True),
    sa.Column('embedding', Embedding(384), nullable=True),
    sa.Column('embed_model', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doc_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doc_chunks_source_document_id'), ['source_document_id'], unique=False)

    if op.get_bind().dialect.name == 'postgresql':
        # Searching documents by meaning and by words (doc 05 §3).
        op.execute("CREATE INDEX ix_doc_chunks_embedding ON doc_chunks USING hnsw (embedding vector_cosine_ops)")
        op.execute("CREATE INDEX ix_doc_chunks_text ON doc_chunks USING gin (to_tsvector('simple', text))")

    op.create_table('facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('attribute', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('academic_year', sa.String(length=9), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('locator', sa.String(length=300), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.create_index('ix_facts_entity_attribute', ['entity_type', 'entity_id', 'attribute'], unique=False)
        batch_op.create_index(batch_op.f('ix_facts_source_document_id'), ['source_document_id'], unique=False)

    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facts_source_document_id'))
        batch_op.drop_index('ix_facts_entity_attribute')

    op.drop_table('facts')
    with op.batch_alter_table('doc_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doc_chunks_source_document_id'))

    op.drop_table('doc_chunks')
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_source_documents_url')
        batch_op.drop_index(batch_op.f('ix_source_documents_source_id'))
        batch_op.drop_index(batch_op.f('ix_source_documents_sha256'))

    op.drop_table('source_documents')
    op.drop_table('sources')
    op.drop_table('okf_loads')
    op.drop_table('fact_conflicts')
    # ### end Alembic commands ###
