"""session summaries record what happened (Phase 7)

Revision ID: a7b7df1187ed
Revises: 5be5f6e26ab1
Create Date: 2026-10-02 15:14:17.584649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a7b7df1187ed'
down_revision: Union[str, None] = '5be5f6e26ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('happened', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'[]'")))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_summaries', schema=None) as batch_op:
        batch_op.drop_column('happened')

    # ### end Alembic commands ###
