"""student target exam

Revision ID: c411ec4ada55
Revises: 1a4822cea615
Create Date: 2026-09-18 10:52:15.164528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c411ec4ada55'
down_revision: Union[str, None] = '1a4822cea615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_exam_code', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('target_exam_code')

    # ### end Alembic commands ###
