"""memory, consent and timeline (Phase 2)

Consent and data requests, profile details (interests, goals, constraints), counselling threads
and session summaries, the event timeline, searchable memory items (pgvector on PostgreSQL) and
per-turn student-state readings. See docs/design/02-database-schema.md §2-5.

Revision ID: c85d25b5c898
Revises: b6e8c3d2f415
Create Date: 2026-10-01 17:29:50.131443

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = 'c85d25b5c898'
down_revision: Union[str, None] = 'b6e8c3d2f415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_by', sa.String(length=20), nullable=False),
    sa.Column('guardian', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('verification', sa.String(length=20), nullable=False),
    sa.Column('notice_version', sa.String(length=20), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('data_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_requests_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('counselling_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('topic_key', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision_status', sa.String(length=20), nullable=False),
    sa.Column('current_position', sa.Text(), nullable=False),
    sa.Column('open_questions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('actions_agreed', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('next_step', sa.Text(), nullable=True),
    sa.Column('opened_session_id', sa.Integer(), nullable=True),
    sa.Column('last_session_id', sa.Integer(), nullable=True),
    sa.Column('last_touched_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['last_session_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['opened_session_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counselling_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counselling_threads_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('memory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON().with_variant(Vector(384), 'postgresql'), nullable=True),
    sa.Column('embed_model', sa.String(length=60), nullable=True),
    sa.Column('salience', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sensitivity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('source_session_id', sa.Integer(), nullable=True),
    sa.Column('evidence_message_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['source_session_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['memory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_items_student_profile_id'), ['student_profile_id'], unique=False)
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("CREATE INDEX ix_memory_items_embedding ON memory_items USING hnsw (embedding vector_cosine_ops)")

    op.create_table('session_summaries',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('important_context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('decisions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('unresolved_questions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('new_interests', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('goals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('next_steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('roadmap_changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('student_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('threads_touched', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    with op.batch_alter_table('session_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_summaries_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('student_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=False),
    sa.Column('sensitivity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['source_session_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_constraints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_constraints_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('student_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=120), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_events_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('student_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['source_session_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_goals_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('student_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('node_key', sa.String(length=120), nullable=True),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_session_id', sa.Integer(), nullable=True),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['source_session_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_interests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_interests_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('turn_analyses',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.String(length=60), nullable=True),
    sa.Column('topic', sa.String(length=120), nullable=True),
    sa.Column('emotion_signals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('underlying_concerns', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('safety', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('turn_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turn_analyses_student_profile_id'), ['student_profile_id'], unique=False)

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education_stage', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('stream', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('study_hours_per_week', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('study_hours_per_week')
        batch_op.drop_column('city')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('stream')
        batch_op.drop_column('education_stage')

    with op.batch_alter_table('turn_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turn_analyses_student_profile_id'))

    op.drop_table('turn_analyses')
    with op.batch_alter_table('student_interests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_interests_student_profile_id'))

    op.drop_table('student_interests')
    with op.batch_alter_table('student_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_goals_student_profile_id'))

    op.drop_table('student_goals')
    with op.batch_alter_table('student_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_events_student_profile_id'))
        batch_op.drop_index(batch_op.f('ix_student_events_occurred_at'))

    op.drop_table('student_events')
    with op.batch_alter_table('student_constraints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_constraints_student_profile_id'))

    op.drop_table('student_constraints')
    with op.batch_alter_table('session_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_summaries_student_profile_id'))

    op.drop_table('session_summaries')
    with op.batch_alter_table('memory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_items_student_profile_id'))

    op.drop_table('memory_items')
    with op.batch_alter_table('counselling_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counselling_threads_student_profile_id'))

    op.drop_table('counselling_threads')
    with op.batch_alter_table('data_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_requests_student_profile_id'))

    op.drop_table('data_requests')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_student_profile_id'))

    op.drop_table('consents')
    # ### end Alembic commands ###
