"""refresh requests

Revision ID: f470369c50fc
Revises: 2d97fb97e535
Create Date: 2026-10-02 12:49:54.490391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f470369c50fc'
down_revision: Union[str, None] = '2d97fb97e535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_requests_college_id'), ['college_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_requests_college_id'))

    op.drop_table('refresh_requests')
    # ### end Alembic commands ###
