"""career knowledge graph (Phase 4)

Nodes and typed edges with their sources, and a record of each load. See
docs/design/04-knowledge-graph.md and 13-phase4-plan.md.

Revision ID: f5da3e325211
Revises: 7255fff01d6b
Create Date: 2026-10-01 20:10:18.489764

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f5da3e325211'
down_revision: Union[str, None] = '7255fff01d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kg_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('aliases', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('attrs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('review', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('kg_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kg_nodes_type'), ['type'], unique=False)

    op.create_table('kg_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('counts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('unmatched', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('nodes', sa.Integer(), nullable=False),
    sa.Column('edges', sa.Integer(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kg_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src_key', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('dst_key', sa.String(length=120), nullable=False),
    sa.Column('attrs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('source', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('review', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['dst_key'], ['kg_nodes.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_key'], ['kg_nodes.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('src_key', 'type', 'dst_key', name='uq_kg_edge')
    )
    with op.batch_alter_table('kg_edges', schema=None) as batch_op:
        batch_op.create_index('ix_kg_edges_dst_type', ['dst_key', 'type'], unique=False)
        batch_op.create_index('ix_kg_edges_src_type', ['src_key', 'type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kg_edges', schema=None) as batch_op:
        batch_op.drop_index('ix_kg_edges_src_type')
        batch_op.drop_index('ix_kg_edges_dst_type')

    op.drop_table('kg_edges')
    op.drop_table('kg_versions')
    with op.batch_alter_table('kg_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kg_nodes_type'))

    op.drop_table('kg_nodes')
    # ### end Alembic commands ###
